spring:
  jpa:
    show-sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password: sa
  h2:
    console:
      enabled: true
      path: /h2-console