server:
  port: 8080
  shutdown: graceful
  max-http-header-size: 48000

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: suni
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    property-naming-strategy: SNAKE_CASE
